### ISSUE TITLE
Many permissions dont have descriptions

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/NameLayer#25]
Let's deprecate the constructor without a description and go through the plugins cleaning up all the ones without one.

**Comment by KaloHG** [comment]
Updated Bastion Permissions.

**Comment by KaloHG** [comment]
All permissions that I could find should be updated. Pull Requests are posted to JukeAlert, and FactoryMod. This should be done.

**Comment by Maxopoly** [comment]
Very cool
